const data = {
    products:[
        {
        // _id: '1',
        name: 'Nike-Slim-Shirt',
        slug: 'nike-slim-shirt0',
        category: 'Shirts',
        image: '/images/p6.jpg',
        price: '120',
        countInStock: '10',
        brand: 'NIKE',
        rating: '4.5',
        numReviews: '10',
        description: 'High Qualtiy Shirt',
        },
        {
        // _id: '2',
        name: 'Adidas-Slim-Shirt',
        slug: 'Adidas-product',
        category: 'Tee-Shirts',
        image: '/images/p3.jpg',
        price: '320',
        countInStock: '12',
        brand: 'Adidas',
        rating: '4.6',
        numReviews: '11',
        description: 'High Qualtiy Tee-Shirt',
        },
        {
        // _id: '3',
        name: 'Puma-Slim-Shirt',
        slug: 'Puma-Pants2',
        category: 'Pants',
        image: '/images/p4.jpg',
        price: '420',
        countInStock: '13',
        brand: 'Puma',
        rating: '4.7',
        numReviews: '12',
        description: 'High Qualtiy Pant',
        },  
        {
        // _id: '4',
        name: 'Levis-Slim-Shirt',
        slug: 'Levis-slim',
        category: 'Trouser',
        image: '/images/p5.jpg',
        price: '220',
        countInStock: '14',
        brand: 'Levis',
        rating: '4.8',
        numReviews: '13',
        description: 'High Qualtiy Trouser',
        },
    ]
}
export default data